In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor
import pandas as pd

In [2]:
data = TabularDataset('diabetes.csv')

In [4]:
predictor = TabularPredictor(label='Outcome').fit(data,num_gpus=1)

No path specified. Models will be saved in: "AutogluonModels/ag-20250517_033656"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.11.9
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #25~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 17:20:50 UTC 2
CPU Count:          16
Memory Avail:       4.96 GB / 15.31 GB (32.4%)
Disk Space Avail:   32.12 GB / 171.96 GB (18.7%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "/home/cismine/GPU_in_ML&DL/AutogluonModels/ag-20250517_033656"
Train Data Rows:    768
Train Data Columns: 8
Label Column:       Outcome
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [1, 0]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5061.84 MB
	Train Data (Original)  Memory Usage: 0.05 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['BMI', 'DiabetesPedigreeFunction']
		('int', [])   : 6 | ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 2 | ['BMI', 'DiabetesPedigreeFunction']
		('int', [])   : 6 | ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', ...]
	0.0s = Fit runtime
	8 features in original data used to generate 8 features in processed data.
	Train Data (Processed) Memory Usage: 0.05 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 614, Val Rows: 154
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif ...
	0.7857	 = Validation score   (accuracy)
	1.52s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7792	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT ...
	Training LightGBMXT with GPU, note that this may negatively impact model quality compared to CPU training.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
	0.8247	 = Validation score   (accuracy)
	9.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Training LightGBM with GPU, note that this may negatively impact model quality compared to CPU training.
	0.8117	 = Validation score   (accuracy)
	2.78s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8182	 = Validation score   (accuracy)
	1.24s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8117	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost ...
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.8117	 = Validation score   (accuracy)
	3.92s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7987	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7987	 = Validation score   (accuracy)
	1.03s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 8: early stopping
	0.8377	 = Validation score   (accuracy)
	5.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [10:37:24] WARNING: /workspace/src/common/error_msg.cc:45: `gpu_id` is deprecated since2.0.0, use `device` instead. E.g. device=cpu/cuda/cuda:0
  warnings.warn(smsg, UserWarning)
/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [10:37:24] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [10:37:25] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [10:37:25] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)
	0.7987	 = Validation score   (accuracy)
	0.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8506	 = Validation score   (accuracy)
	6.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Training LightGBMLarge with GPU, note that this may negatively impact model quality compared to CPU training.
	0.7922	 = Validation score   (accuracy)
	15.8s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.667, 'NeuralNetFastAI': 0.333}
	0.8571	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 50.99s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 5295.6 rows/s (154 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (154 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/cismine/GPU_in_ML&DL/AutogluonModels/ag-20250517_033656")

In [5]:
test = pd.read_csv('diabetes.csv')
test.drop(columns=['Outcome'])

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [6]:
predictor.evaluate(test, silent=True)

/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/fastai/learner.py:455: UserWarning: load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.
If you only need to load model weights and optimizer state, use the safe `Learner.load` instead.
  warn("load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.\nIf you only need to load model weights and optimizer state, use the safe `Learner.load` instead.")

{'accuracy': 0.8450520833333334,
 'balanced_accuracy': 0.8100149253731344,
 'mcc': 0.6510499579911259,
 'roc_auc': 0.9101940298507464,
 'f1': 0.7576374745417516,
 'precision': 0.8340807174887892,
 'recall': 0.6940298507462687}

In [7]:
predictor.leaderboard(test)

/home/cismine/anaconda3/envs/ML_GPU/lib/python3.11/site-packages/fastai/learner.py:455: UserWarning: load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.
If you only need to load model weights and optimizer state, use the safe `Learner.load` instead.
  warn("load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.\nIf you only need to load model weights and optimizer state, use the safe `Learner.load` instead.")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestGini,0.963542,0.818182,accuracy,0.161471,0.095204,1.235477,0.161471,0.095204,1.235477,1,True,5
1,RandomForestEntr,0.962240,0.811688,accuracy,0.156716,0.107323,1.104968,0.156716,0.107323,1.104968,1,True,6
2,ExtraTreesGini,0.959635,0.798701,accuracy,0.148382,0.063278,0.761318,0.148382,0.063278,0.761318,1,True,8
3,ExtraTreesEntr,0.959635,0.798701,accuracy,0.162995,0.100528,1.028217,0.162995,0.100528,1.028217,1,True,9
4,LightGBMLarge,0.958333,0.792208,accuracy,0.014015,0.002126,15.803642,0.014015,0.002126,15.803642,1,True,13
5,KNeighborsDist,0.955729,0.779221,accuracy,0.018240,0.019425,0.019210,0.018240,0.019425,0.019210,1,True,2
6,XGBoost,0.937500,0.798701,accuracy,0.068041,0.007902,0.863746,0.068041,0.007902,0.863746,1,True,11
7,LightGBM,0.878906,0.811688,accuracy,0.003582,0.001219,2.781041,0.003582,0.001219,2.781041,1,True,4
8,CatBoost,0.858073,0.811688,accuracy,0.006444,0.002681,3.924838,0.006444,0.002681,3.924838,1,True,7
9,NeuralNetTorch,0.848958,0.850649,accuracy,0.047966,0.006679,6.501864,0.047966,0.006679,6.501864,1,True,12
10,LightGBMXT,0.846354,0.824675,accuracy,0.005641,0.001346,9.577350,0.005641,0.001346,9.577350,1,True,3
11,WeightedEnsemble_L2,0.845052,0.857143,accuracy,0.082367,0.029081,11.594593,0.003187,0.000734,0.082103,2,True,14
12,NeuralNetFastAI,0.805990,0.837662,accuracy,0.031214,0.021668,5.010626,0.031214,0.021668,5.010626,1,True,10
13,KNeighborsUnif,0.787760,0.785714,accuracy,0.019658,0.018720,1.524209,0.019658,0.018720,1.524209,1,True,1